language: android
jdk: openjdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.1

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew check

before_install:
 - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
